-- UP

CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NUll,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);
    
CREATE TABLE FOLLOWERS(
    USER_ID INTEGER,
    FOLLOWER_ID INTEGER
);

CREATE TABLE ACTIVITIES(
    USER_ID INTEGER NOT NULL,
    ACTIVITY_TYPE_ID TEXT NOT NULL,
    ACTIVITY_PAYLOAD NOT NULL
);


INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('jose', 'jose@marin', 'password');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('rich', 'rich@hill', 'password');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('randy', 'randy@rod', 'password');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('default_user', 'user@email', 'password');


INSERT INTO FOLLOWERS (USER_ID, FOLLOWER_ID) VALUES (1,2);
INSERT INTO FOLLOWERS (USER_ID, FOLLOWER_ID) VALUES (2,3);
INSERT INTO FOLLOWERS (USER_ID, FOLLOWER_ID) VALUES (3,1);
INSERT INTO FOLLOWERS (USER_ID, FOLLOWER_ID) VALUES (4,1);

INSERT INTO ACTIVITIES (USER_ID, ACTIVITY_TYPE_ID, ACTIVITY_PAYLOAD) VALUES (1, 'url', 'https://c1.staticflickr.com/8/7693/17123251389_bed3c3a1ba_b.jpg');
INSERT INTO ACTIVITIES (USER_ID, ACTIVITY_TYPE_ID, ACTIVITY_PAYLOAD) VALUES (1, 'text', 'this is a post');
INSERT INTO ACTIVITIES (USER_ID, ACTIVITY_TYPE_ID, ACTIVITY_PAYLOAD) VALUES (2, 'url', 'http://imgur.com/gallery/pqGR8D6');
INSERT INTO ACTIVITIES (USER_ID, ACTIVITY_TYPE_ID, ACTIVITY_PAYLOAD) VALUES (3, 'text', 'another post');
INSERT INTO ACTIVITIES (USER_ID, ACTIVITY_TYPE_ID, ACTIVITY_PAYLOAD) VALUES (4, 'text', 'another post');

-- DOWN

DROP TABLE USERS;
DROP TABLE FOLLOWERS;
DROP TABLE ACTIVITIES;
