-- UP

CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NUll, 
    PASSWORD VARCHAR(100) NOT NULL
);
    
CREATE TABLE FOLLOWERS(
    USER_ID INTEGER,
    FOLLOWER_ID INTEGER
);

CREATE TABLE ACTIVITIES(
    USER_ID INTEGER NOT NULL,
    ACTIVITY_TYPE_ID TEXT NOT NULL,
    ACTIVITY_PAYLOAD NOT NULL
);

CREATE TABLE POSTS (
    ID             INTEGER   PRIMARY KEY,
    DESCRIPTION    TEXT      NOT NULL,
    URL            TEXT      NOT NULL
);








-- DOWN

DROP TABLE USERS;
DROP TABLE FOLLOWERS;
DROP TABLE ACTIVITIES;
DROP TABLE POSTS;
