-- UP

CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NUll,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);
    
CREATE TABLE FOLLOWERS(
    USER_ID INTEGER,
    FOLLOWER_ID INTEGER
);

CREATE TABLE ACTIVITIES(
    USER_ID INTEGER NOT NULL,
    ACTIVITY_TYPE_ID TEXT NOT NULL,
    ACTIVITY_PAYLOAD NOT NULL
);

CREATE TABLE POSTS (
    ID  INTEGER PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL,
    URL TEXT NOT NULL
);

INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('jose', 'jose@email.com', 'password');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('rich', 'rich@email.com', 'password');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('randy', 'randy@email.com', 'password');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES ('taq', 'taq@foobar', 'password');


INSERT INTO FOLLOWERS (USER_ID, FOLLOWER_ID) VALUES (1,2);
INSERT INTO FOLLOWERS (USER_ID, FOLLOWER_ID) VALUES (2,3);
INSERT INTO FOLLOWERS (USER_ID, FOLLOWER_ID) VALUES (3,4);


-- DOWN

DROP TABLE USERS;
DROP TABLE FOLLOWERS;
DROP TABLE ACTIVITIES;
DROP TABLE POSTS;
